headersOrigin = "config"
redirectsOrigin = "config"

[functions]

[functions."*"]

[[plugins]]
origin = "ui"
package = "@netlify/plugin-lighthouse"
pinned_version = "6"

[plugins.inputs]

[[plugins]]
origin = "default"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[build]
publish = "/Volumes/External-2TB/Projects/service-site-builder/sites/5-star-roofing/out"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"

[build.environment]
NETLIFY_NEXT_PLUGIN_SKIP = "true"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/_next/static/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/images/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/photos/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.jpg"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.png"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.avif"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.webp"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.css"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.js"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.html"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
from = "/hail-damage-roof-repair-in-amarillo"
to = "/hail-damage-repair-amarillo-tx"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/hail-damage-roof-repair-in-amarillo/"
to = "/hail-damage-repair-amarillo-tx/"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/hail-damage-roof-repair-amarillo-texas"
to = "/hail-damage-repair-amarillo-tx"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/hail-damage-roof-repair-amarillo-texas/"
to = "/hail-damage-repair-amarillo-tx/"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/hail-damage-roofs-in-amarillo"
to = "/hail-damage-repair-amarillo-tx"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/hail-damage-roofs-in-amarillo/"
to = "/hail-damage-repair-amarillo-tx/"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/roof-hail-damage-repair-services-in-amarillo-tx"
to = "/hail-damage-repair-amarillo-tx"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/roof-hail-damage-repair-services-in-amarillo-tx/"
to = "/hail-damage-repair-amarillo-tx/"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/hail-damage-roof-repair-midland-texas"
to = "/hail-damage-repair-midland-tx"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/hail-damage-roof-repair-midland-texas/"
to = "/hail-damage-repair-midland-tx/"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/hail-damage-roof-repair-odessa-texas"
to = "/hail-damage-repair-odessa-tx"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/hail-damage-roof-repair-odessa-texas/"
to = "/hail-damage-repair-odessa-tx/"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/hail-damage-roof-repair-lubbock-texas"
to = "/hail-damage-repair-lubbock-tx"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/hail-damage-roof-repair-lubbock-texas/"
to = "/hail-damage-repair-lubbock-tx/"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/residential-roofing-amarillo-texas"
to = "/residential-roofing-amarillo"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/residential-roofing-amarillo-texas/"
to = "/residential-roofing-amarillo/"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/residential-roofing-amarillo-tx"
to = "/residential-roofing-amarillo"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/residential-roofing-amarillo-tx/"
to = "/residential-roofing-amarillo/"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/residential-roofing-in-amarillo"
to = "/residential-roofing-amarillo"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/residential-roofing-in-amarillo/"
to = "/residential-roofing-amarillo/"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/commercial-roofing-amarillo-tx"
to = "/commercial-roofing-amarillo"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/commercial-roofing-amarillo-tx/"
to = "/commercial-roofing-amarillo/"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/commercial-roofing-lubbock-texas"
to = "/commercial-roofing-lubbock"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/commercial-roofing-lubbock-texas/"
to = "/commercial-roofing-lubbock/"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/commercial-roofing-midland-texas"
to = "/commercial-roofing-midland"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/commercial-roofing-midland-texas/"
to = "/commercial-roofing-midland/"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/commercial-roofing-odessa-texas"
to = "/commercial-roofing-odessa"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/commercial-roofing-odessa-texas/"
to = "/commercial-roofing-odessa/"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/emergency-roof-repair-odessa-texas"
to = "/emergency-roof-repair-odessa"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/emergency-roof-repair-odessa-texas/"
to = "/emergency-roof-repair-odessa/"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/roof-storm-damage-in-amarillo"
to = "/storm-damage-roof-repair-in-amarillo"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/roof-storm-damage-in-amarillo/"
to = "/storm-damage-roof-repair-in-amarillo/"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/roof-wind-damage-in-amarillo"
to = "/wind-damage-roof-repair-in-amarillo"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/roof-wind-damage-in-amarillo/"
to = "/wind-damage-roof-repair-in-amarillo/"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/canyon-tx-roofing"
to = "/canyon-texas-roofing"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/canyon-tx-roofing/"
to = "/canyon-texas-roofing/"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]